import SectionHeader from "@/components/shared/sectionHeader/SectionHeader";
import {
  Accordion,
  AccordionContent,
  AccordionItem,
  AccordionTrigger,
} from "@/components/ui/accordion";

const faqs = [
  {
    question: "How do I create an event on PLANORA?",
    answer:
      "Creating an event is simple. Sign up for an organizer account, head to your dashboard, and click 'Create Event'. Follow the step-by-step guide to set your dates, location, ticket options, and customize your event page.",
  },
  {
    question: "When do I get paid for my ticket sales?",
    answer:
      "Payments are processed securely via our payment partners. You can choose to receive rolling payouts during your ticket sales period or get a lump sum transfer 3-5 days after your event concludes.",
  },
  {
    question: "Can I manage check-ins at the door?",
    answer:
      "Yes! Every ticket generated by PLANORA includes a unique QR code. You can use our mobile app to quickly scan attendees in and track real-time attendance.",
  },
  {
    question: "Are there any hidden fees?",
    answer:
      "No hidden fees. We charge a small transparent percentage per ticket sold. You can choose to absorb this fee or pass it on to your ticket buyers during checkout.",
  },
  {
    question: "Can I cancel my event and issue refunds?",
    answer:
      "Absolutely. Our platform allows you to issue full or partial refunds with just a few clicks. If you cancel an event, you can automatically notify all attendees and trigger bulk refunds.",
  },
];

const FAQ = () => {
  return (
    <section className="py-20 bg-white dark:bg-transparent">
      <div className="container mx-auto px-4 max-w-4xl">

        <SectionHeader
          align="center"
          title="Frequently Asked Questions"
          description="Got questions? We've got answers. Here are the most common questions we hear from our organizers and attendees."
        />

        <div className="bg-white dark:bg-gray-900  shadow-sm border border-gray-100 dark:border-gray-800 p-6 md:p-10">
          <Accordion type="single" collapsible className="w-full">
            {faqs.map((faq, index) => (
              <AccordionItem key={index} value={`item-${index}`}>
                <AccordionTrigger className="text-lg font-semibold hover:no-underline hover:text-orange-400 dark:hover:text-blue-400 transition-colors">
                  {faq.question}
                </AccordionTrigger>
                <AccordionContent className="text-gray-600 dark:text-gray-400 text-base leading-relaxed">
                  {faq.answer}
                </AccordionContent>
              </AccordionItem>
            ))}
          </Accordion>
        </div>
      </div>
    </section>
  );
};

export default FAQ;
