import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { spaceGrotesk } from "./fonts";
import { AuthProvider } from "@/context/AuthProvider";

const geistSans = Geist({
     variable: "--font-geist-sans",
     subsets: ["latin"],
});

const geistMono = Geist_Mono({
     variable: "--font-geist-mono",
     subsets: ["latin"],
});

export const metadata: Metadata = {
     title: "Planora",
     description: "Generated by create next app",
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <html lang="en">
               <body
                    className={`${spaceGrotesk.className} font-sans `}
               >
                    <AuthProvider>
                         <Toaster richColors />
                              {children}
                    </AuthProvider>
               </body>
          </html>
     );
}