import type { Metadata } from "next";
import "./globals.css";
import { Toaster } from "@/components/ui/sonner";
import { spaceGrotesk } from "./fonts";
import { AuthProvider } from "@/context/AuthProvider";



export const metadata: Metadata = {
     title: "PLANORA",
     description: "Generated by create next app",
};

export default function RootLayout({
     children,
}: Readonly<{
     children: React.ReactNode;
}>) {
     return (
          <html lang="en">
               <body
                    className={`${spaceGrotesk.className} bg-[#f7f7f7] font-sans `}
               >
                         <AuthProvider>
                              <Toaster richColors />
                              {children}
                         </AuthProvider>
               </body>
          </html>
     );
}